name: Build Morpheus

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Update packages
      run: sudo apt-get update -qq
      
    - name: Install dependencies
      run: sudo apt-get install -qq -y build-essential flex-old

    - name: Make
      run: bash -c "cd src/ && CFLAGS='-std=gnu89 -fcommon' make && make install"

    - name: strip
      run: bash -c "strip bin/morpheus cp bin/morpheus dist/bin/platform/Linux_x86-gcc4"
